#!/bin/bash
# Build N1 Parser Standalone v2
# Concatenates and cleans up module references

set -e

OUTPUT="parser_full.fox"
TMP="/tmp/parser_build.tmp"

echo "Building N1 Parser (standalone v2)..."

# Start with header
cat > "$OUTPUT" << 'HEADER'
# N1 Parser - Full Standalone Version
# Auto-generated by build_parser_v2.sh  
# All dependencies inlined for N0 compatibility

HEADER

# 1. Token constants and Token struct (from lexer.fox)
echo "# Token Constants & Struct" >> "$OUTPUT"
sed -n '/^var TOKEN_ILLEGAL/,/^var TOKEN_KASUS = 62/p' lexer.fox >> "$OUTPUT"
echo "" >> "$OUTPUT"
sed -n '/^struktur Token$/,/^akhir$/p' lexer.fox >> "$OUTPUT"
echo "" >> "$OUTPUT"

# 2. Token helper function
echo "fungsi new_token(token_type int, literal string, line int, column int) Token" >> "$OUTPUT"
echo "    kembalikan Token{" >> "$OUTPUT"  
echo "        token_type: token_type," >> "$OUTPUT"
echo "        literal: literal," >> "$OUTPUT"
echo "        line: line," >> "$OUTPUT"
echo "        column: column," >> "$OUTPUT"
echo "        has_leading_space: salah" >> "$OUTPUT"
echo "    }" >> "$OUTPUT"
echo "akhir" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# 3. AST (skip comments, full file)
echo "# AST Node Types & Structures" >> "$OUTPUT"
tail -n +4 ast.fox >> "$OUTPUT"
echo "" >> "$OUTPUT"

# 4. Parser (skip imports, remove module prefixes)
echo "# Parser Implementation" >> "$OUTPUT"
grep -v "^ambil " parser.fox | \
  sed 's/lexer\.Lexer/Lexer/g' | \
  sed 's/token\.Token/Token/g' | \
  sed 's/token\.TOKEN_/TOKEN_/g' | \
  sed 's/ast\.//g' | \
  sed 's/lexer\.LexerNextToken/LexerNextToken/g' | \
  sed 's/token\.MakeToken/new_token/g' >> "$OUTPUT"

echo "✓ Built: $OUTPUT"
wc -l "$OUTPUT"
