#!/bin/bash
# Build N1 Parser Standalone
# Concatenates all dependencies into single file for N0 compatibility

set -e

OUTPUT="parser_full.fox"
echo "Building N1 Parser (standalone)..."

# Start with header
cat > "$OUTPUT" << 'HEADER'
# N1 Parser - Full Standalone Version
# Auto-generated by build_parser.sh
# All dependencies inlined for N0 compatibility
# DO NOT EDIT MANUALLY - regenerate with build_parser.sh

HEADER

# Extract sections from lexer.fox (only what parser needs)
echo "# ============================================================================" >> "$OUTPUT"
echo "# TOKEN CONSTANTS & STRUCTURES (from lexer.fox)" >> "$OUTPUT"
echo "# ============================================================================" >> "$OUTPUT"
sed -n '/^var TOKEN_/,/^var TOKEN_KASUS = 62/p' lexer.fox >> "$OUTPUT"
echo "" >> "$OUTPUT"
sed -n '/^struktur Token$/,/^akhir$/p' lexer.fox >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Add AST (full file, it's standalone)
echo "# ============================================================================" >> "$OUTPUT"
echo "# AST NODES (from ast.fox)" >> "$OUTPUT"
echo "# ============================================================================" >> "$OUTPUT"
tail -n +4 ast.fox >> "$OUTPUT"  # Skip first 3 lines (comments)
echo "" >> "$OUTPUT"

# Add parser core (skip imports)
echo "# ============================================================================" >> "$OUTPUT"
echo "# PARSER IMPLEMENTATION (from parser.fox)" >> "$OUTPUT"
echo "# ============================================================================" >> "$OUTPUT"
sed -n '/^# ============================================================================/,$ p' parser.fox | \
  grep -v "^ambil " >> "$OUTPUT"

echo "✓ Built: $OUTPUT"
wc -l "$OUTPUT"
