#include "morph.h"

// Native bindings
void mph_native_print(MorphContext* ctx, MorphString* s);
void mph_native_print_int(MorphContext* ctx, mph_int n);
mph_int mph_string_index(MorphContext* ctx, MorphString* s, MorphString* sub);
MorphString* mph_string_trim(MorphContext* ctx, MorphString* s, MorphString* cut);
MorphArray* mph_string_split(MorphContext* ctx, MorphString* s, MorphString* sep);

// Struct Definitions

// RTTI Definitions

// Type IDs

// Struct Definitions (Env & Types)

// Global Variables

// Function Prototypes
void mph_gen_header(MorphContext* ctx, void* _env_void);
void mph_gen_data(MorphContext* ctx, void* _env_void);
void mph_gen_text(MorphContext* ctx, void* _env_void);
void mph_gen_start(MorphContext* ctx, void* _env_void);
void mph_gen_main(MorphContext* ctx, void* _env_void);
void mph_main(MorphContext* ctx, void* _env_void);

// Function Definitions
void mph_gen_header(MorphContext* ctx, void* _env_void) {
	mph_native_print(ctx, mph_string_new(ctx, "; Generated by N1 Transpiler\n"));
	mph_native_print(ctx, mph_string_new(ctx, "; Signature: V Z O E L F O XS\n\n"));
}

void mph_gen_data(MorphContext* ctx, void* _env_void) {
	mph_native_print(ctx, mph_string_new(ctx, "section .data\n"));
	mph_native_print(ctx, mph_string_new(ctx, "    signature db \"V Z O E L F O XS\", 0\n\n"));
}

void mph_gen_text(MorphContext* ctx, void* _env_void) {
	mph_native_print(ctx, mph_string_new(ctx, "section .text\n"));
	mph_native_print(ctx, mph_string_new(ctx, "    global _start\n\n"));
}

void mph_gen_start(MorphContext* ctx, void* _env_void) {
	mph_native_print(ctx, mph_string_new(ctx, "_start:\n"));
	mph_native_print(ctx, mph_string_new(ctx, "    call main\n"));
	mph_native_print(ctx, mph_string_new(ctx, "    mov rdi, rax\n"));
	mph_native_print(ctx, mph_string_new(ctx, "    mov rax, 60\n"));
	mph_native_print(ctx, mph_string_new(ctx, "    syscall\n\n"));
}

void mph_gen_main(MorphContext* ctx, void* _env_void) {
	mph_native_print(ctx, mph_string_new(ctx, "main:\n"));
	mph_native_print(ctx, mph_string_new(ctx, "    push rbp\n"));
	mph_native_print(ctx, mph_string_new(ctx, "    mov rbp, rsp\n"));
	mph_native_print(ctx, mph_string_new(ctx, "    mov rax, 42\n"));
	mph_native_print(ctx, mph_string_new(ctx, "    pop rbp\n"));
	mph_native_print(ctx, mph_string_new(ctx, "    ret\n"));
}

void mph_main(MorphContext* ctx, void* _env_void) {
	mph_gen_header(ctx, NULL);
	mph_gen_data(ctx, NULL);
	mph_gen_text(ctx, NULL);
	mph_gen_start(ctx, NULL);
	mph_gen_main(ctx, NULL);
}


// Entry Point
void morph_entry_point(MorphContext* ctx) {
	mph_main(ctx, NULL);
}
